FROM node:current-alpine3.22 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

FROM node:current-alpine3.22
WORKDIR /app
COPY --from=builder /app .
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 3000
CMD ["node", "bot-stats-server.js"]
