apiVersion: apps/v1
kind: Deployment
metadata:
  name: aivisspeech-engine
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: aivisspeech-engine
  template:
    metadata:
      labels:
        app: aivisspeech-engine
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
      initContainers:
        - name: copy-models
          image: busybox:latest
          command: ['/bin/sh', '-c']
          args:
            - |
              mkdir -p /aivisspeech-data/Models
              mkdir -p /aivisspeech-data/Logs
              cp -r /models/* /aivisspeech-data/Models/ 2>/dev/null || echo "No models to copy or directory already exists"
              chown -R 1000:1000 /aivisspeech-data
              ls -la /aivisspeech-data/Models/
          volumeMounts:
            - name: aivisspeech-data
              mountPath: /aivisspeech-data
            - name: models-data
              mountPath: /models
      containers:
        - name: aivisspeech-engine
          image: ghcr.io/aivis-project/aivisspeech-engine:nvidia-latest
          ports:
            - containerPort: 10101
          volumeMounts:
            - name: aivisspeech-data
              mountPath: /home/user/.local/share/AivisSpeech-Engine-Dev
            - name: models-data
              mountPath: /models
          resources:
            requests:
              nvidia.com/gpu: "1"
              memory: "2Gi"
              cpu: "1000m"
            limits:
              nvidia.com/gpu: "1"
              memory: "4Gi"
              cpu: "2000m"
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
      volumes:
        - name: aivisspeech-data
          hostPath:
            path: /home/alec/aivisspeech-data
            type: DirectoryOrCreate
        - name: models-data
          hostPath:
            path: /home/alec/models
            type: Directory
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: aivisspeech-engine
spec:
  type: NodePort
  ports:
    - port: 10101
      targetPort: 10101
      nodePort: 30101
  selector:
    app: aivisspeech-engine