apiVersion: apps/v1
kind: Deployment
metadata:
  name: aivis-chan-bot-web
  labels:
    app: aivis-chan-bot-web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: aivis-chan-bot-web
  template:
    metadata:
      labels:
        app: aivis-chan-bot-web
    spec:
      containers:
      - name: aivis-chan-bot-web
        image: ghcr.io/alexandergg-0520/aivis-chan-bot-web:latest
        ports:
        - containerPort: 3001 # Astro SSRサーバーが3001番でリッスン
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: aivis-chan-bot-web-env
---
apiVersion: v1
kind: Service
metadata:
  name: aivis-chan-bot-web
spec:
  type: ClusterIP
  selector:
    app: aivis-chan-bot-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
