# Aivis-chan Bot 1st - ConfigMap Example
apiVersion: v1
kind: ConfigMap
metadata:
  name: aivis-chan-bot-1st-config
data:
  config.json: |
    {
      "TOKEN": "YOUR_DISCORD_BOT_1ST_TOKEN_HERE",
      "clientId": "YOUR_CLIENT_ID_HERE",
      "PATREON": {
        "CLIENT_ID": "YOUR_PATREON_CLIENT_ID_HERE",
        "CLIENT_SECRET": "YOUR_PATREON_CLIENT_SECRET_HERE",
        "REDIRECT_URI": "https://your-domain.github.io/your-bot/callback"
      },
      "TTS_HOST": "aivisspeech-engine",
      "TTS_PORT": 10101,
      "TTS_TIMEOUT": 15000,
      "TTS_MAX_RETRIES": 3,
      "TTS_RETRY_DELAY": 1000,
      "sentry": {
        "dsn": "YOUR_SENTRY_DSN_HERE",
        "environment": "production",
        "tracesSampleRate": 1.0,
        "enabled": true
      },
      "ALTERNATE_GEMINI_MODEL_ID": "gemini-2.5-pro-preview-05-06",
      "ALTERNATE_MODEL_UNTIL": "2025-05-20",
      "ALTERNATE_GEMINI_MODEL_VERSION": "001",
      "GEMINI_SERVICE_ACCOUNT_PATH": "your-service-account.json",
      "GEMINI_PROJECT_ID": "your-project-id",
      "GEMINI_LOCATION": "us-central1",
      "GEMINI_MODEL_ID": "gemini-1.5-pro-002",
      "speechEngineUrl": "http://aivisspeech-engine:10101"
    }

---
# Aivis-chan Bot 2nd - ConfigMap Example
apiVersion: v1
kind: ConfigMap
metadata:
  name: aivis-chan-bot-2nd-config
data:
  config.json: |
    {
      "TOKEN": "YOUR_DISCORD_BOT_2ND_TOKEN_HERE",
      "clientId": "YOUR_CLIENT_ID_HERE",
      "PATREON": {
        "CLIENT_ID": "YOUR_PATREON_CLIENT_ID_HERE",
        "CLIENT_SECRET": "YOUR_PATREON_CLIENT_SECRET_HERE",
        "REDIRECT_URI": "https://your-domain.github.io/your-bot/callback"
      },
      "TTS_HOST": "aivisspeech-engine",
      "TTS_PORT": 10101,
      "TTS_TIMEOUT": 15000,
      "TTS_MAX_RETRIES": 3,
      "TTS_RETRY_DELAY": 1000,
      "sentry": {
        "dsn": "YOUR_SENTRY_DSN_HERE",
        "environment": "production",
        "tracesSampleRate": 1.0,
        "enabled": true
      },
      "ALTERNATE_GEMINI_MODEL_ID": "gemini-2.5-pro-preview-05-06",
      "ALTERNATE_MODEL_UNTIL": "2025-05-20",
      "ALTERNATE_GEMINI_MODEL_VERSION": "001",
      "GEMINI_SERVICE_ACCOUNT_PATH": "your-service-account.json",
      "GEMINI_PROJECT_ID": "your-project-id",
      "GEMINI_LOCATION": "us-central1",
      "GEMINI_MODEL_ID": "gemini-1.5-pro-002",
      "speechEngineUrl": "http://aivisspeech-engine:10101"
    }

---
# Aivis-chan Bot 3rd - ConfigMap Example
apiVersion: v1
kind: ConfigMap
metadata:
  name: aivis-chan-bot-3rd-config
data:
  config.json: |
    {
      "TOKEN": "YOUR_DISCORD_BOT_3RD_TOKEN_HERE",
      "clientId": "YOUR_CLIENT_ID_HERE",
      "PATREON": {
        "CLIENT_ID": "YOUR_PATREON_CLIENT_ID_HERE",
        "CLIENT_SECRET": "YOUR_PATREON_CLIENT_SECRET_HERE",
        "REDIRECT_URI": "https://your-domain.github.io/your-bot/callback"
      },
      "TTS_HOST": "aivisspeech-engine",
      "TTS_PORT": 10101,
      "TTS_TIMEOUT": 15000,
      "TTS_MAX_RETRIES": 3,
      "TTS_RETRY_DELAY": 1000,
      "sentry": {
        "dsn": "YOUR_SENTRY_DSN_HERE",
        "environment": "production",
        "tracesSampleRate": 1.0,
        "enabled": true
      },
      "ALTERNATE_GEMINI_MODEL_ID": "gemini-2.5-pro-preview-05-06",
      "ALTERNATE_MODEL_UNTIL": "2025-05-20",
      "ALTERNATE_GEMINI_MODEL_VERSION": "001",
      "GEMINI_SERVICE_ACCOUNT_PATH": "your-service-account.json",
      "GEMINI_PROJECT_ID": "your-project-id",
      "GEMINI_LOCATION": "us-central1",
      "GEMINI_MODEL_ID": "gemini-1.5-pro-002",
      "speechEngineUrl": "http://aivisspeech-engine:10101"
    }

---
# Aivis-chan Bot 4th - ConfigMap Example
apiVersion: v1
kind: ConfigMap
metadata:
  name: aivis-chan-bot-4th-config
data:
  config.json: |
    {
      "TOKEN": "YOUR_DISCORD_BOT_4TH_TOKEN_HERE",
      "clientId": "YOUR_CLIENT_ID_HERE",
      "PATREON": {
        "CLIENT_ID": "YOUR_PATREON_CLIENT_ID_HERE",
        "CLIENT_SECRET": "YOUR_PATREON_CLIENT_SECRET_HERE",
        "REDIRECT_URI": "https://your-domain.github.io/your-bot/callback"
      },
      "TTS_HOST": "aivisspeech-engine",
      "TTS_PORT": 10101,
      "TTS_TIMEOUT": 15000,
      "TTS_MAX_RETRIES": 3,
      "TTS_RETRY_DELAY": 1000,
      "sentry": {
        "dsn": "YOUR_SENTRY_DSN_HERE",
        "environment": "production",
        "tracesSampleRate": 1.0,
        "enabled": true
      },
      "ALTERNATE_GEMINI_MODEL_ID": "gemini-2.5-pro-preview-05-06",
      "ALTERNATE_MODEL_UNTIL": "2025-05-20",
      "ALTERNATE_GEMINI_MODEL_VERSION": "001",
      "GEMINI_SERVICE_ACCOUNT_PATH": "your-service-account.json",
      "GEMINI_PROJECT_ID": "your-project-id",
      "GEMINI_LOCATION": "us-central1",
      "GEMINI_MODEL_ID": "gemini-1.5-pro-002",
      "speechEngineUrl": "http://aivisspeech-engine:10101"
    }

---
# Aivis-chan Bot 5th - ConfigMap Example
apiVersion: v1
kind: ConfigMap
metadata:
  name: aivis-chan-bot-5th-config
data:
  config.json: |
    {
      "TOKEN": "YOUR_DISCORD_BOT_5TH_TOKEN_HERE",
      "clientId": "YOUR_CLIENT_ID_HERE",
      "PATREON": {
        "CLIENT_ID": "YOUR_PATREON_CLIENT_ID_HERE",
        "CLIENT_SECRET": "YOUR_PATREON_CLIENT_SECRET_HERE",
        "REDIRECT_URI": "https://your-domain.github.io/your-bot/callback"
      },
      "TTS_HOST": "aivisspeech-engine",
      "TTS_PORT": 10101,
      "TTS_TIMEOUT": 15000,
      "TTS_MAX_RETRIES": 3,
      "TTS_RETRY_DELAY": 1000,
      "sentry": {
        "dsn": "YOUR_SENTRY_DSN_HERE",
        "environment": "production",
        "tracesSampleRate": 1.0,
        "enabled": true
      },
      "ALTERNATE_GEMINI_MODEL_ID": "gemini-2.5-pro-preview-05-06",
      "ALTERNATE_MODEL_UNTIL": "2025-05-20",
      "ALTERNATE_GEMINI_MODEL_VERSION": "001",
      "GEMINI_SERVICE_ACCOUNT_PATH": "your-service-account.json",
      "GEMINI_PROJECT_ID": "your-project-id",
      "GEMINI_LOCATION": "us-central1",
      "GEMINI_MODEL_ID": "gemini-1.5-pro-002",
      "speechEngineUrl": "http://aivisspeech-engine:10101"
    }

---
# Aivis-chan Bot 6th - ConfigMap Example
apiVersion: v1
kind: ConfigMap
metadata:
  name: aivis-chan-bot-6th-config
data:
  config.json: |
    {
      "TOKEN": "YOUR_DISCORD_BOT_6TH_TOKEN_HERE",
      "clientId": "YOUR_CLIENT_ID_HERE",
      "PATREON": {
        "CLIENT_ID": "YOUR_PATREON_CLIENT_ID_HERE",
        "CLIENT_SECRET": "YOUR_PATREON_CLIENT_SECRET_HERE",
        "REDIRECT_URI": "https://your-domain.github.io/your-bot/callback"
      },
      "TTS_HOST": "aivisspeech-engine",
      "TTS_PORT": 10101,
      "TTS_TIMEOUT": 15000,
      "TTS_MAX_RETRIES": 3,
      "TTS_RETRY_DELAY": 1000,
      "sentry": {
        "dsn": "YOUR_SENTRY_DSN_HERE",
        "environment": "production",
        "tracesSampleRate": 1.0,
        "enabled": true
      },
      "ALTERNATE_GEMINI_MODEL_ID": "gemini-2.5-pro-preview-05-06",
      "ALTERNATE_MODEL_UNTIL": "2025-05-20",
      "ALTERNATE_GEMINI_MODEL_VERSION": "001",
      "GEMINI_SERVICE_ACCOUNT_PATH": "your-service-account.json",
      "GEMINI_PROJECT_ID": "your-project-id",
      "GEMINI_LOCATION": "us-central1",
      "GEMINI_MODEL_ID": "gemini-1.5-pro-002",
      "speechEngineUrl": "http://aivisspeech-engine:10101"
    }
