name: BuildKit Docker Build

on:
  push:
    branches: ["3rd"]
  pull_request:
    branches: ["3rd"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: aivis-chan-bot-3rd

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Set up BuildKit environment
        run: |
          # Install BuildKit binaries
          BUILDKIT_VERSION="v0.15.1"
          curl -L "https://github.com/moby/buildkit/releases/download/${BUILDKIT_VERSION}/buildkit-${BUILDKIT_VERSION}.linux-amd64.tar.gz" | sudo tar -xzC /usr/local
          
          # Create buildkit directory with proper permissions
          sudo mkdir -p /run/buildkit
          sudo chmod 755 /run/buildkit
          
          # Start buildkitd daemon with proper permissions
          sudo /usr/local/bin/buildkitd --oci-worker=false --containerd-worker=false --addr unix:///run/buildkit/buildkitd.sock --root /tmp/buildkit-root --oci-worker-no-process-sandbox &
          
          # Wait for socket to be created and set permissions
          timeout=30
          while [ ! -S /run/buildkit/buildkitd.sock ] && [ $timeout -gt 0 ]; do
            sleep 1
            timeout=$((timeout - 1))
          done
          
          if [ ! -S /run/buildkit/buildkitd.sock ]; then
            echo "BuildKitd failed to start"
            exit 1
          fi
          
          # Set proper permissions on socket
          sudo chmod 666 /run/buildkit/buildkitd.sock

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build with BuildKit
        run: |
          # Set BUILDKIT_HOST for buildctl
          export BUILDKIT_HOST=unix:///run/buildkit/buildkitd.sock
          
          # Build and push the image
          /usr/local/bin/buildctl build \
            --frontend dockerfile.v0 \
            --local context=. \
            --local dockerfile=. \
            --output type=image,name=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest,push=true \
            --output type=image,name=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }},push=true